### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Jialiang14** [jihunhamm/bilevel-penalty#2]
Hi, I am very interested in your work. I major in hyper-parameters optimization and neural architecture search. These could be modeled into bi-level optimization problem. Could your proposed method be directly applied these problem?
Look forward to your answer.
Best wishes.

**Comment by akshaymehra24** [comment]
Hi @Jialiang14 , yes our method is generic and can be used to solve these bilevel problems. In the paper, we show the formulation for hyperparameter optimization as a bilevel problem and demonstrate the effectiveness of our method on some of the popular applications. Please check the [paper](https://arxiv.org/abs/1911.03432) for more details of our approach.
